##业务应用端口及其他配置
server:
  port: 10006
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
  servlet:
    context-path: /zb_fk_screen_frontend

##服务注册与发现配置
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://10.40.70.90:18761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    #instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
#spring全局配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  application:
    name: zb_fk_screen_frontend
  mvc:
    view:
      prefix: /
      suffix: .jsp

  #分布式session配置
  redis:
    host: 172.28.1.130
    port: 16379
    password: ENCSM4CBC(f/qWCfYvHnbc7QHafFFCkQ==)
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456


#gatewayURL: http://127.0.0.1:10036

gatewayURL2: http://127.0.0.1:10040

#平台服务配置
px:
  #公共数据库SCHEMA配置
  schema: rmcp
  #业务数据库SCHEMA配置
  appSchema: rmcp
  #附件 非结构化环境配置
  uds:
    trackerServer: localhost:22122 #FASTDFS tracker服务地址（需要配置）
    appId: f44801765c2b11ea88d002426a3dc31d
    disabled: true
    connectTimeout: 100
    networkTimeout: 100
    charset: iso8859-1
    trackerHttpPort: 80
    antiStealToken: true
    secretKey: FastDFS1234567890
    maxConnectionCount: 100  #最大连接数
    maxWaitTime: 10  #最大超时时间,单位：秒g
    fileService: simpleFileService #noTableFileService, simpleFileService, udsFileService
    type: fastdfs
  #数据库配置
  datasource:
    dataSource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.28.1.130:13306/pi6000?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: ENCSM4CBC(f/qWCfYvHnbc7QHafFFCkQ==)
      initialSize: 20
      maxActive: 30
#    dataSource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/pi6000?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLocalSessionState=true&serverTimezone=GMT%2B8
#      username: root
#      password: zpproot
#      initialSize: 5
#      maxActive: 20
#    dataSource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/pi6000?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLocalSessionState=true&serverTimezone=GMT%2B8
#      username: root
#      password: zpproot
#      initialSize: 5
#      maxActive: 20


#PI6000组件直连地址
#pi6000-ua-web: 39.98.246.39:8091
#pi6000-mdl-web: 39.98.246.39:8092
#pi6000-bpm-web: 39.98.246.39:8093
#pi6000-uds-web: 39.98.246.39:8095

#PI6000组件直连地址
pi6000-ua-web: 172.28.1.254:18091
pi6000-mdl-web: 172.28.1.254:18092
pi6000-bpm-web: 172.28.1.254:18093
pi6000-task-web: 172.28.1.254:18094
#指定rest直连的ip地址
hostUrl: 172.28.1.225

#业务appID
appId: b23b101faea611e98ddc0242ac110005
#业务组织体系id
orgSystemId: e6455d5fb74611e99595005056835b0c
#uds下载url地址
uds-download-url: http://39.98.246.39:18096/pi6000-uds-web/api/file/udsFileService/download
uds-upload-url: http://39.98.246.39:18096/pi6000-uds-web/api/file/udsFileService/upload
uds-delete-url: http://39.98.246.39:18096/pi6000-uds-web/api/file/udsFileService/delete

#安全风险感知模块
gatewayURL: http://127.0.0.1:10036/

isc:
  appId: 2c905b667839cd2d0178aa08f27a0ab0 #业务系统在ISC的编码
  rootMenuId: 2c905b667839cd2d0178aa08f27a0ab0 #菜单根节点ID
  sso: http://sgcc.isc.com:22001/isc_sso/  #ISC登录地址
  frontServ: http://sgcc.isc.com:22001/isc_frontmv_serv #ISC服务端资源接口地址
  busiUrl: http://127.0.0.1:10006/zb_fk_screen_frontend/ #风控系统入口地址
  isCache: true #是否开启缓存日志,需要与ISC服务端保持一致
  jmsUrl: failover\\:(tcp\\://jms.isc.com\\:61616) #如果isCache为true，此处必须配置
  jmsTopic: AGENT_MQ_40288cd66068cfe501606d96b4d85101 #如果isCache为true，此处必须配置
  menuMode: isc #菜单获取方式


mybatis:
  mapper-locations: classpath:mybatis/dao/*.xml
  configuration:
    call-setters-on-nulls: true
logging:
  path: ./d/zblog