server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由 跳转到服务提供者
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 即服务提供者的微服务名称
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 即服务提供者的微服务名称
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            - After=2022-02-22T10:38:23.449+08:00[Asia/Shanghai] #从当前时间之后可以请求成功  应用场景上线时间设置
#            - Cookie=username,zzyy  #带有用户名的请求
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/