server:
  port: 8087


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-drive-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zpproot
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-drive-user
#    mybatis-plus控制台打印
logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
